name: Spotless Check

on: [push]

jobs:
  spotless_check_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run spotlessCheck
        run: ./gradlew spotlessCheck
