on: [push]

jobs:
  check_lint_job:
    runs-on: ubuntu-latest
    name: Spotless Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Spotless Check
        run: ./gradlew spotlessCheck
